=== Chlumsky/msdf-atlas-gen/font_descriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "atlas": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "distanceRange": {
          "type": "number"
        },
        "distanceRangeMiddle": {
          "type": "number"
        },
        "size": {
          "type": "number"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "yOrigin": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "distanceRange",
        "distanceRangeMiddle",
        "size",
        "width",
        "height",
        "yOrigin"
      ]
    },
    "metrics": {
      "type": "object",
      "properties": {
        "emSize": {
          "type": "number"
        },
        "lineHeight": {
          "type": "number"
        },
        "ascender": {
          "type": "number"
        },
        "descender": {
          "type": "number"
        },
        "underlineY": {
          "type": "number"
        },
        "underlineThickness": {
          "type": "number"
        }
      },
      "required": [
        "emSize",
        "lineHeight",
        "ascender",
        "descender",
        "underlineY",
        "underlineThickness"
      ]
    },
    "glyphs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "index": {
            "type": "number"
          },
          "advance": {
            "type": "number"
          },
          "planeBounds": {
            "type": "object",
            "properties": {
              "left": {
                "type": "number"
              },
              "bottom": {
                "type": "number"
              },
              "right": {
                "type": "number"
              },
              "top": {
                "type": "number"
              }
            },
            "required": [
              "left",
              "bottom",
              "right",
              "top"
            ]
          },
          "atlasBounds": {
            "type": "object",
            "properties": {
              "left": {
                "type": "number"
              },
              "bottom": {
                "type": "number"
              },
              "right": {
                "type": "number"
              },
              "top": {
                "type": "number"
              }
            },
            "required": [
              "left",
              "bottom",
              "right",
              "top"
            ]
          }
        },
        "required": [
          "index",
          "advance"
        ]
      }
    },
    "kerning": {
      "type": "array",
      "items": {}
    }
  },
  "required": [
    "atlas",
    "metrics",
    "glyphs",
    "kerning"
  ]
}

=== Chlumsky/msdf-atlas-gen/output/SF-Pro-Display_msdf.json
{"atlas":{"type":"msdf","distanceRange":4,"distanceRangeMiddle":0,"size":48,"width":996,"height":996,"yOrigin":"bottom"},"metrics":{"emSize":1,"lineHeight":1.193359375,"ascender":0.9521484375,"descender":-0.2412109375,"underlineY":-0.1806640625,"underlineThickness":0.05859375},"glyphs":[{"index":2,"advance":0},{"index":3,"advance":0.205078125},{"index":4,"advance":0.205078125},{"index":5,"advance":0.1025390625},{"index":6,"advance":0.5},{"index":7,"advance":1},{"index":8,"advance":0.5},{"index":9,"advance":1},{"index":10,"advance":0.3330078125},{"index":11,"advance":0.25},{"index":12,"advance":0.166015625},{"index":13,"advance":0.6044921875},{"index":14,"advance":0.21484375},{"index":15,"advance":0.1025390625},{"index":16,"advance":0.05126953125},{"index":17,"advance":0},{"index":18,"advance":0.22216796875},{"index":19,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.76041666666666663},"atlasBounds":{"left":933.5,"bottom":309.5,"right":967.5,"top":348.5}},{"index":20,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":926.5,"bottom":735.5,"right":960.5,"top":783.5}},{"index":21,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":961.5,"bottom":735.5,"right":995.5,"top":783.5}},{"index":22,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.92708333333333326},"atlasBounds":{"left":601.5,"bottom":538.5,"right":635.5,"top":585.5}},{"index":23,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.96875},"atlasBounds":{"left":183.5,"bottom":894.5,"right":217.5,"top":943.5}},{"index":24,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.96875},"atlasBounds":{"left":218.5,"bottom":894.5,"right":252.5,"top":943.5}},{"index":25,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.98958333333333326},"atlasBounds":{"left":799.5,"bottom":945.5,"right":833.5,"top":995.5}},{"index":26,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":146.5,"bottom":684.5,"right":180.5,"top":732.5}},{"index":27,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":1.0104166666666665},"atlasBounds":{"left":183.5,"bottom":944.5,"right":217.5,"top":995.5}},{"index":28,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.96875},"atlasBounds":{"left":253.5,"bottom":894.5,"right":287.5,"top":943.5}},{"index":29,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.28125,"right":0.67179361979166663,"top":0.76041666666666652},"atlasBounds":{"left":834.5,"bottom":945.5,"right":868.5,"top":995.5}},{"index":30,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":181.5,"bottom":684.5,"right":215.5,"top":732.5}},{"index":31,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.23958333333333334,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":207.5,"bottom":786.5,"right":241.5,"top":843.5}},{"index":32,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":1.0104166666666665},"atlasBounds":{"left":218.5,"bottom":944.5,"right":252.5,"top":995.5}},{"index":33,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":1.0104166666666665},"atlasBounds":{"left":253.5,"bottom":944.5,"right":287.5,"top":995.5}},{"index":34,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":1.0104166666666665},"atlasBounds":{"left":288.5,"bottom":944.5,"right":322.5,"top":995.5}},{"index":35,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":1.0104166666666665},"atlasBounds":{"left":323.5,"bottom":944.5,"right":357.5,"top":995.5}},{"index":36,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":216.5,"bottom":684.5,"right":250.5,"top":732.5}},{"index":37,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":1.0104166666666665},"atlasBounds":{"left":358.5,"bottom":944.5,"right":392.5,"top":995.5}},{"index":38,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":1.0104166666666665},"atlasBounds":{"left":393.5,"bottom":944.5,"right":427.5,"top":995.5}},{"index":39,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":1.0104166666666665},"atlasBounds":{"left":428.5,"bottom":944.5,"right":462.5,"top":995.5}},{"index":40,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.23958333333333334,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":242.5,"bottom":786.5,"right":276.5,"top":843.5}},{"index":41,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":251.5,"bottom":684.5,"right":285.5,"top":732.5}},{"index":42,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":286.5,"bottom":684.5,"right":320.5,"top":732.5}},{"index":43,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":321.5,"bottom":684.5,"right":355.5,"top":732.5}},{"index":44,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.23958333333333334,"right":0.67179361979166663,"top":0.76041666666666652},"atlasBounds":{"left":384.5,"bottom":684.5,"right":418.5,"top":732.5}},{"index":45,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.96875},"atlasBounds":{"left":288.5,"bottom":894.5,"right":322.5,"top":943.5}},{"index":46,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.94791666666666652},"atlasBounds":{"left":419.5,"bottom":684.5,"right":453.5,"top":732.5}},{"index":47,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.052083333333333336,"right":0.67179361979166663,"top":0.90625},"atlasBounds":{"left":758.5,"bottom":442.5,"right":792.5,"top":488.5}},{"index":48,"advance":0.63525390625,"planeBounds":{"left":-0.033610026041666664,"bottom":-0.28125,"right":0.67472330729166663,"top":0.76041666666666652},"atlasBounds":{"left":869.5,"bottom":945.5,"right":903.5,"top":995.5}},{"index":49,"advance":0.63525390625,"planeBounds":{"left":-0.036539713541666664,"bottom":-0.13541666666666669,"right":0.67179361979166663,"top":0.84374999999999989},"atlasBounds":{"left":664.5,"bottom":538.5,"right":698.5,"top":585.5}},{"index":50,"advance":0.6044921875,"planeBounds":{"left":0.01871744791666663,"bottom":-0.052083333333333336,"right":0.62288411458333326,"top":0.76041666666666663},"atlasBounds":{"left":506.5,"bottom":268.5,"right":535.5,"top":307.5}},{"index":51,"advance":0.6044921875,"planeBounds":{"left":0.01871744791666663,"bottom":-0.21875,"right":0.62288411458333326,"top":0.76041666666666663},"atlasBounds":{"left":699.5,"bottom":538.5,"right":728.5,"top":585.5}},{"index":52,"advance":0.6044921875,"planeBounds":{"left":0.01871744791666663,"bottom":-0.23958333333333334,"right":0.62288411458333326,"top":0.76041666666666652},"atlasBounds":{"left":454.5,"bottom":684.5,"right":483.5,"top":732.5}},{"index":53,"advance":0.6044921875,"planeBounds":{"left":0.01871744791666663,"bottom":-0.052083333333333336,"right":0.62288411458333326,"top":0.94791666666666652},"atlasBounds":{"left":484.5,"bottom":684.5,"right":513.5,"top":732.5}},{"index":54,"advance":0.73388671875,"planeBounds":{"left":-0.039632161458333336,"bottom":-0.052083333333333336,"right":0.75203450520833326,"top":0.76041666666666663},"atlasBounds":{"left":62.5,"bottom":492.5,"right":100.5,"top":531.5}},{"index":55,"advance":0.68603515625,"planeBounds":{"left":-0.0082194010416666661,"bottom":-0.072916666666666657,"right":0.70011393229166663,"top":0.76041666666666663},"atlasBounds":{"left":855.5,"bottom":353.5,"right":889.5,"top":393.5}},{"index":56,"advance":0.68603515625,"planeBounds":{"left":-0.0082194010416666661,"bottom":-0.072916666666666657,"right":0.70011393229166663,"top":0.94791666666666663},"atlasBounds":{"left":323.5,"bottom":894.5,"right":357.5,"top":943.5}},{"index":57,"advance":0.68603515625,"planeBounds":{"left":-0.0082194010416666661,"bottom":-0.072916666666666657,"right":0.70011393229166663,"top":0.94791666666666663},"atlasBounds":{"left":358.5,"bottom":894.5,"right":392.5,"top":943.5}},{"index":58,"advance":0.68603515625,"planeBounds":{"left":-0
